[package]
name = "installer"
version = "0.1.0"
edition = "2024"

[dependencies]
eframe = "0.27"
egui = "0.27"
which = "5"
winreg = "0.11"
reqwest = { version = "0.11", features = ["blocking", "json"] }
serde_json = "1.0"
